# Generated by Django 4.0.4 on 2022-05-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('channel_code_name', models.CharField(max_length=24)),
                ('admin_id', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('region', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('commander_id', models.IntegerField()),
                ('commander_code_name', models.CharField(blank=True, max_length=24, null=True)),
                ('password', models.CharField(max_length=16)),
                ('donations', models.IntegerField()),
                ('admin', models.BooleanField(default=False)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('title', models.CharField(max_length=24)),
                ('summary', models.TextField(blank=True, max_length=400, null=True)),
                ('media_id', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('urgency', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_url', models.URLField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_id', models.IntegerField()),
                ('qr_code', models.URLField()),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('url_count_hit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_id', models.IntegerField()),
                ('qr_code', models.IntegerField()),
                ('source_id', models.IntegerField()),
                ('code_name', models.CharField(blank=True, max_length=24, null=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('reputation', models.IntegerField()),
                ('locale', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=16)),
                ('donations', models.IntegerField()),
                ('qr_code_status', models.BooleanField()),
            ],
        ),
    ]
