# Generated by Django 4.0.4 on 2022-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchestrator_id', models.IntegerField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Commander',
        ),
        migrations.DeleteModel(
            name='IntelItem',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
